---
- hosts: all
  become: yes
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Install latest version of Apache
      yum:
        name: httpd
        state: latest
      notify:
      - restart httpd

    - name: Ensure Apache is running
      service:
        name: httpd
        state: started

    - name: Install "Development tools" package group
      yum:
        name: "@Development tools"
        state: present

  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted 
