---

- name: yum upgrade all packages
  yum:
    name: '*'
    state: latest

- name: yum install "epel-release"
  yum:
    name: epel-release
    state: present

- name: yum install "Development tools" package group
  yum:
    name: "@Development tools"
    state: present
 
- name: yum install "Net Tools"
  yum:
    name: net-tools
    state: latest 

- name: yum install "htop"
  yum:
    name: htop
    state: latest
 
- name: yum install "Vim"
  yum:
    name: vim-enhanced 
    state: latest

- name: yum install "wget"
  yum:
    name: wget 
    state: present

- name: pip install "docker-py"
  pip:
    name: docker-py 
